[project]
name = "voice-summarizer"
version = "0.1.0"
description = "Voice Summarizer - Audio and video file transcription with AI summarization."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.109.1",
    "python-dotenv>=1.1.1",
]
